/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportesRouteImport } from './routes/reportes'
import { Route as PreInformesRouteImport } from './routes/pre-informes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistorialRouteImport } from './routes/historial'
import { Route as FeriadosRouteImport } from './routes/feriados'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CalificacionesRouteImport } from './routes/calificaciones'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PreInformesIndexRouteImport } from './routes/pre-informes.index'
import { Route as CalificacionesIndexRouteImport } from './routes/calificaciones.index'
import { Route as PreInformesReporteRouteImport } from './routes/pre-informes.reporte'
import { Route as PreInformesAlumnoRouteImport } from './routes/pre-informes.alumno'
import { Route as CalificacionesReporteRouteImport } from './routes/calificaciones.reporte'
import { Route as CalificacionesBoletinRouteImport } from './routes/calificaciones.boletin'

const ReportesRoute = ReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => rootRouteImport,
} as any)
const PreInformesRoute = PreInformesRouteImport.update({
  id: '/pre-informes',
  path: '/pre-informes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistorialRoute = HistorialRouteImport.update({
  id: '/historial',
  path: '/historial',
  getParentRoute: () => rootRouteImport,
} as any)
const FeriadosRoute = FeriadosRouteImport.update({
  id: '/feriados',
  path: '/feriados',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CalificacionesRoute = CalificacionesRouteImport.update({
  id: '/calificaciones',
  path: '/calificaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PreInformesIndexRoute = PreInformesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PreInformesRoute,
} as any)
const CalificacionesIndexRoute = CalificacionesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CalificacionesRoute,
} as any)
const PreInformesReporteRoute = PreInformesReporteRouteImport.update({
  id: '/reporte',
  path: '/reporte',
  getParentRoute: () => PreInformesRoute,
} as any)
const PreInformesAlumnoRoute = PreInformesAlumnoRouteImport.update({
  id: '/alumno',
  path: '/alumno',
  getParentRoute: () => PreInformesRoute,
} as any)
const CalificacionesReporteRoute = CalificacionesReporteRouteImport.update({
  id: '/reporte',
  path: '/reporte',
  getParentRoute: () => CalificacionesRoute,
} as any)
const CalificacionesBoletinRoute = CalificacionesBoletinRouteImport.update({
  id: '/boletin',
  path: '/boletin',
  getParentRoute: () => CalificacionesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calificaciones': typeof CalificacionesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/feriados': typeof FeriadosRoute
  '/historial': typeof HistorialRoute
  '/login': typeof LoginRoute
  '/pre-informes': typeof PreInformesRouteWithChildren
  '/reportes': typeof ReportesRoute
  '/calificaciones/boletin': typeof CalificacionesBoletinRoute
  '/calificaciones/reporte': typeof CalificacionesReporteRoute
  '/pre-informes/alumno': typeof PreInformesAlumnoRoute
  '/pre-informes/reporte': typeof PreInformesReporteRoute
  '/calificaciones/': typeof CalificacionesIndexRoute
  '/pre-informes/': typeof PreInformesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/feriados': typeof FeriadosRoute
  '/historial': typeof HistorialRoute
  '/login': typeof LoginRoute
  '/reportes': typeof ReportesRoute
  '/calificaciones/boletin': typeof CalificacionesBoletinRoute
  '/calificaciones/reporte': typeof CalificacionesReporteRoute
  '/pre-informes/alumno': typeof PreInformesAlumnoRoute
  '/pre-informes/reporte': typeof PreInformesReporteRoute
  '/calificaciones': typeof CalificacionesIndexRoute
  '/pre-informes': typeof PreInformesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calificaciones': typeof CalificacionesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/feriados': typeof FeriadosRoute
  '/historial': typeof HistorialRoute
  '/login': typeof LoginRoute
  '/pre-informes': typeof PreInformesRouteWithChildren
  '/reportes': typeof ReportesRoute
  '/calificaciones/boletin': typeof CalificacionesBoletinRoute
  '/calificaciones/reporte': typeof CalificacionesReporteRoute
  '/pre-informes/alumno': typeof PreInformesAlumnoRoute
  '/pre-informes/reporte': typeof PreInformesReporteRoute
  '/calificaciones/': typeof CalificacionesIndexRoute
  '/pre-informes/': typeof PreInformesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calificaciones'
    | '/dashboard'
    | '/feriados'
    | '/historial'
    | '/login'
    | '/pre-informes'
    | '/reportes'
    | '/calificaciones/boletin'
    | '/calificaciones/reporte'
    | '/pre-informes/alumno'
    | '/pre-informes/reporte'
    | '/calificaciones/'
    | '/pre-informes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/feriados'
    | '/historial'
    | '/login'
    | '/reportes'
    | '/calificaciones/boletin'
    | '/calificaciones/reporte'
    | '/pre-informes/alumno'
    | '/pre-informes/reporte'
    | '/calificaciones'
    | '/pre-informes'
  id:
    | '__root__'
    | '/'
    | '/calificaciones'
    | '/dashboard'
    | '/feriados'
    | '/historial'
    | '/login'
    | '/pre-informes'
    | '/reportes'
    | '/calificaciones/boletin'
    | '/calificaciones/reporte'
    | '/pre-informes/alumno'
    | '/pre-informes/reporte'
    | '/calificaciones/'
    | '/pre-informes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalificacionesRoute: typeof CalificacionesRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  FeriadosRoute: typeof FeriadosRoute
  HistorialRoute: typeof HistorialRoute
  LoginRoute: typeof LoginRoute
  PreInformesRoute: typeof PreInformesRouteWithChildren
  ReportesRoute: typeof ReportesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reportes': {
      id: '/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof ReportesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pre-informes': {
      id: '/pre-informes'
      path: '/pre-informes'
      fullPath: '/pre-informes'
      preLoaderRoute: typeof PreInformesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historial': {
      id: '/historial'
      path: '/historial'
      fullPath: '/historial'
      preLoaderRoute: typeof HistorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feriados': {
      id: '/feriados'
      path: '/feriados'
      fullPath: '/feriados'
      preLoaderRoute: typeof FeriadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calificaciones': {
      id: '/calificaciones'
      path: '/calificaciones'
      fullPath: '/calificaciones'
      preLoaderRoute: typeof CalificacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pre-informes/': {
      id: '/pre-informes/'
      path: '/'
      fullPath: '/pre-informes/'
      preLoaderRoute: typeof PreInformesIndexRouteImport
      parentRoute: typeof PreInformesRoute
    }
    '/calificaciones/': {
      id: '/calificaciones/'
      path: '/'
      fullPath: '/calificaciones/'
      preLoaderRoute: typeof CalificacionesIndexRouteImport
      parentRoute: typeof CalificacionesRoute
    }
    '/pre-informes/reporte': {
      id: '/pre-informes/reporte'
      path: '/reporte'
      fullPath: '/pre-informes/reporte'
      preLoaderRoute: typeof PreInformesReporteRouteImport
      parentRoute: typeof PreInformesRoute
    }
    '/pre-informes/alumno': {
      id: '/pre-informes/alumno'
      path: '/alumno'
      fullPath: '/pre-informes/alumno'
      preLoaderRoute: typeof PreInformesAlumnoRouteImport
      parentRoute: typeof PreInformesRoute
    }
    '/calificaciones/reporte': {
      id: '/calificaciones/reporte'
      path: '/reporte'
      fullPath: '/calificaciones/reporte'
      preLoaderRoute: typeof CalificacionesReporteRouteImport
      parentRoute: typeof CalificacionesRoute
    }
    '/calificaciones/boletin': {
      id: '/calificaciones/boletin'
      path: '/boletin'
      fullPath: '/calificaciones/boletin'
      preLoaderRoute: typeof CalificacionesBoletinRouteImport
      parentRoute: typeof CalificacionesRoute
    }
  }
}

interface CalificacionesRouteChildren {
  CalificacionesBoletinRoute: typeof CalificacionesBoletinRoute
  CalificacionesReporteRoute: typeof CalificacionesReporteRoute
  CalificacionesIndexRoute: typeof CalificacionesIndexRoute
}

const CalificacionesRouteChildren: CalificacionesRouteChildren = {
  CalificacionesBoletinRoute: CalificacionesBoletinRoute,
  CalificacionesReporteRoute: CalificacionesReporteRoute,
  CalificacionesIndexRoute: CalificacionesIndexRoute,
}

const CalificacionesRouteWithChildren = CalificacionesRoute._addFileChildren(
  CalificacionesRouteChildren,
)

interface PreInformesRouteChildren {
  PreInformesAlumnoRoute: typeof PreInformesAlumnoRoute
  PreInformesReporteRoute: typeof PreInformesReporteRoute
  PreInformesIndexRoute: typeof PreInformesIndexRoute
}

const PreInformesRouteChildren: PreInformesRouteChildren = {
  PreInformesAlumnoRoute: PreInformesAlumnoRoute,
  PreInformesReporteRoute: PreInformesReporteRoute,
  PreInformesIndexRoute: PreInformesIndexRoute,
}

const PreInformesRouteWithChildren = PreInformesRoute._addFileChildren(
  PreInformesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalificacionesRoute: CalificacionesRouteWithChildren,
  DashboardRoute: DashboardRoute,
  FeriadosRoute: FeriadosRoute,
  HistorialRoute: HistorialRoute,
  LoginRoute: LoginRoute,
  PreInformesRoute: PreInformesRouteWithChildren,
  ReportesRoute: ReportesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
